baseURL: https://jeffreyportfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Jeffrey Kaikati
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get Started
    subtitle: |-
            Welcome to my Portfolio Website!
            
    title: Hi, my name is Jeffrey
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: 29 Surrey Quays Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jkaikati.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (033) 767434549
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/jeffrey.kaikati/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/jeffkaikati/
#      - icon: fa-github
#        label: GitHub
#        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jeffrey-kaikati/
#  image: ''
#  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
    
      - image: Photo-pro-compressed.jpg
        subtitle: Details about me 
        title: About me
        url: blogs/homework1
        
        
      - image: fond_ext1.jpg
        subtitle: A few of personal and group projects from engineering school
        title: CentraleSupélec Projects
        url: blogs/homework2
        
        
      - image: lbs.jpeg
        subtitle: A few of personal and group projects from business school
        title: London Business School Projects
        url: blogs/portfolio
        
        
      - image: wp6611193.jpg
        subtitle: Download my CV
        title: CV
        url: blogs/cv
        
        
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
        
        
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I am a CentraleSupélec Paris engineer with a solid background in Data Science, Mathematics and Business Management. 
            Currently enrolled at London Business School, I am reading for the Masters in Analytics and Management, 
            and aim to start my career in Strategy Consulting."
    title: My background and aspirations
    url: blogs
